Repository miong/MakeYourChoices, pull requests merged in 2020-04, with the labels that each got.

#4 [DEV] Add table feature
  src/html_engine/main.js
  src/html_engine/style.css
  src/ink/engine/credits.ink
  src/ink/engine/engine.ink
Labels: enhancement

#9 Law paragraphs
  src/html_engine/main.js
  src/ink/scenes/arrive_to_lake_side.ink
  src/ink/scenes/introduction.ink
  src/ink/scenes/lake_stuff.ink
  src/ink/scenes/my_house.ink
  src/ink/scenes/road_to_lake_side.ink
  src/ink/scenes/the_drivers_kitchen.ink
  src/ink/scenes/the_hungry_grizzly.ink
Labels: Quality, enhancement

#13 Deepscan issue correction
  src/html_engine/main.js
Labels: Quality

#16 [DOC] Mergify badge correction
  .mergify.yml
  README.md
Labels: documentation, md, merge-when-green

#17 [DOC] Update README.md
  README.md
Labels: documentation, md, merge-when-green

#10 [DEV] create a story debugger
  src/ink/scenes/arrive_to_lake_side.ink
  src/ink/scenes/my_house.ink
  src/ink/scenes/road_to_lake_side.ink
  src/ink/scenes/the_drivers_kitchen.ink
  src/ink/scenes/the_hungry_grizzly.ink
  tools/story_debugger/debugger.html
  tools/story_debugger/main.js
  tools/story_debugger/treant-js-master/LICENSE
  tools/story_debugger/treant-js-master/README.md
  tools/story_debugger/treant-js-master/Treant.css
  tools/story_debugger/treant-js-master/Treant.js
  tools/story_debugger/treant-js-master/build
  tools/story_debugger/treant-js-master/package.json
  tools/story_debugger/treant-js-master/vendor/jquery.easing.js
  tools/story_debugger/treant-js-master/vendor/jquery.min.js
  tools/story_debugger/treant-js-master/vendor/jquery.mousewheel.js
  tools/story_debugger/treant-js-master/vendor/perfect-scrollbar/perfect-scrollbar.css
  tools/story_debugger/treant-js-master/vendor/perfect-scrollbar/perfect-scrollbar.js
  tools/story_debugger/treant-js-master/vendor/raphael.js
Labels: enhancement, ink, js, md, merge-when-green

#21 [DEV] Correction for save function
  src/ink/engine/functions.ink
  src/ink/engine/variables.ink
Labels: enhancement, ink, merge-when-green
